import { NUMBERS_BY_WORD } from "./index.js";

const lines = [
  ["four", "9", "one"],
  ["8", "two", "seven", "three"],
  ["6", "six", "six", "two"],
  ["4", "four", "4", "5", "seven", "7", "nine", "7", "two"],
  ["six", "4"],
  ["5", "6"],
  ["three", "4"],
  ["6", "5", "four", "eight", "five"],
  ["8", "eight"],
  ["6", "1", "7", "2", "5"],
  ["7", "2", "five"],
  ["9", "1", "6", "7", "6"],
  ["4", "nine", "3", "6", "four"],
  ["2", "7", "9"],
  ["nine", "eight", "six", "five", "seven", "1"],
  ["two", "eight", "6", "four"],
  ["8"],
  ["six", "three", "7"],
  ["3", "9", "4", "8", "two", "2"],
  ["5", "2", "eight", "9", "five", "five", "six"],
  ["2", "6", "nine"],
  ["2", "eight", "1", "nine"],
  ["two", "one", "7"],
  ["5"],
  ["one", "three", "1", "two", "six"],
  ["2", "eight", "3", "six", "1"],
  ["nine", "five", "5", "2", "seven"],
  ["six", "nine", "7", "five"],
  ["four", "1", "1", "6"],
  ["3", "4", "four", "seven", "4"],
  ["3", "5", "2", "3", "two"],
  ["five", "three", "4", "six"],
  ["7", "six", "6"],
  ["six", "four", "9"],
  ["3", "1", "2"],
  ["four", "9"],
  ["two", "two", "8", "four"],
  ["1", "2", "seven", "six"],
  ["seven", "9", "6"],
  ["6", "three", "6", "5"],
  ["six", "6", "four"],
  ["two", "3"],
  ["seven", "6", "5", "9"],
  ["three", "two", "3", "1"],
  ["four", "4", "9", "8"],
  ["eight", "5", "one", "4", "3", "eight", "5"],
  ["1", "6"],
  ["8", "three", "five", "one", "nine"],
  ["6", "4", "1", "one"],
  ["four", "6", "seven", "eight"],
  ["5"],
  ["7", "4", "1"],
  ["9", "6", "four", "4"],
  ["1", "two", "six", "4"],
  ["seven", "nine", "7", "eight", "one"],
  ["4"],
  ["3", "1", "five", "6", "one", "3"],
  ["5", "9", "2"],
  ["6", "9", "two", "five", "1", "seven"],
  ["two", "3", "six", "5"],
  ["four", "6", "9", "3", "six", "five", "4"],
  ["two", "1", "5", "7", "5", "one"],
  ["eight", "five", "3", "one", "one", "two"],
  ["3", "eight", "6", "4", "six"],
  ["5", "four"],
  ["nine", "1"],
  ["9", "7", "6", "2", "1", "seven"],
  ["two", "seven", "one", "3", "six", "4", "two"],
  ["9", "seven", "four"],
  ["two", "6", "seven", "nine", "2", "7", "three", "7", "8"],
  ["six", "9"],
  ["seven", "4", "3"],
  ["4", "9"],
  ["nine", "eight", "three", "seven", "eight", "9"],
  ["three", "seven", "2", "8"],
  ["9", "five", "nine"],
  ["three", "3"],
  ["5", "6", "4", "8", "seven"],
  ["two", "3", "two", "7", "nine", "1", "6"],
  ["five", "six", "1", "4", "1"],
  ["6", "6", "eight", "two", "four"],
  ["1", "2"],
  ["two", "nine", "8", "4", "six", "three"],
  ["six", "6"],
  ["7", "8", "five", "nine"],
  ["8", "8"],
  ["7", "3", "two"],
  ["8", "8", "3", "6"],
  ["5", "nine", "five"],
  ["eight", "nine", "4", "9", "6", "5"],
  ["6", "two", "6", "three", "eight"],
  ["2", "1", "8", "4", "three", "three", "3", "four"],
  ["3", "four", "nine", "four"],
  ["1", "seven"],
  ["1", "5", "six", "one", "8", "5"],
  ["two", "six", "5", "six", "seven"],
  ["eight", "six", "9"],
  ["seven", "two", "4"],
  ["4", "6", "two", "3"],
  ["8", "five", "3", "four", "six"],
  ["4", "7", "nine", "seven", "eight", "6", "7"],
  ["nine", "four", "1"],
  ["1", "6", "six", "3", "8", "nine", "2"],
  ["9", "9", "2", "four", "two"],
  ["3", "five", "6", "eight", "three", "six", "6"],
  ["5", "seven", "six"],
  ["five", "seven", "three", "4", "two"],
  ["two", "seven", "1", "5"],
  ["2"],
  ["9", "8", "6", "5", "2", "one", "5"],
  ["6", "7", "nine", "eight", "4"],
  ["eight", "7", "seven"],
  ["three", "three", "5", "5"],
  ["one", "1", "9", "9", "4", "7"],
  ["nine", "3", "6", "three"],
  ["4", "2", "2"],
  ["5", "7", "9", "6"],
  ["5", "2", "1", "seven", "9", "four", "1"],
  ["8", "2", "four"],
  ["eight", "7", "5", "nine", "five"],
  ["two", "9", "two"],
  ["3", "four", "one", "3"],
  ["8", "one", "six", "9"],
  ["two", "six", "5", "5", "six", "5"],
  ["four", "three", "4", "8"],
  ["6"],
  ["5", "2", "4"],
  ["six", "8", "4", "9", "two"],
  ["four", "four", "eight", "6", "eight", "seven", "nine"],
  ["5"],
  ["6", "5", "7", "2", "one"],
  ["9", "6", "3"],
  ["one", "three", "3"],
  ["2", "five", "8", "9", "eight", "three"],
  ["2", "one", "eight", "one", "five", "2", "nine"],
  ["3", "9", "eight", "3", "4", "eight", "4"],
  ["six", "8", "three", "2", "five", "9"],
  ["5"],
  ["4", "8", "seven", "one", "six", "eight", "seven", "five"],
  ["two", "3", "4"],
  ["3", "7"],
  ["9", "four", "two", "9", "2", "8", "five"],
  ["seven", "4"],
  ["nine", "3", "seven", "6"],
  ["5", "four", "6", "2"],
  ["3", "1", "five", "seven", "1", "5"],
  ["two", "8", "six", "four", "five", "nine", "two"],
  ["five", "six", "three", "7"],
  ["9", "seven", "eight", "five"],
  ["1", "5"],
  ["8", "4", "6", "7", "five"],
  ["2", "five", "two", "one", "three"],
  ["three", "3", "9", "four", "3"],
  ["5", "seven"],
  ["5", "1", "eight", "three", "four", "four"],
  ["two", "9", "one"],
  ["eight", "8"],
  ["five", "2"],
  ["6", "3", "3", "5", "4", "nine"],
  ["4", "six", "2", "1", "4", "five"],
  ["four", "1", "7", "nine", "9", "2"],
  ["3", "six", "seven"],
  ["six", "5", "6", "8", "five"],
  ["two", "three", "five", "seven", "9"],
  ["five", "7", "9", "five", "5"],
  ["seven", "5", "1", "8", "six", "nine", "4"],
  ["five", "six", "2", "5", "7"],
  ["5", "five"],
  ["6", "five"],
  ["2", "six", "3", "2", "six"],
  ["one", "nine", "6", "three", "six"],
  ["nine", "nine", "2", "seven"],
  ["nine", "5", "3", "1", "one", "4", "1", "4"],
  ["9", "four"],
  ["6", "2", "nine", "six", "eight"],
  ["eight", "1", "one", "3"],
  ["5", "2", "9"],
  ["one", "1", "six", "eight", "eight", "1", "seven", "six"],
  ["two", "nine", "three", "8", "two"],
  ["one", "4"],
  ["one", "7", "nine", "seven", "seven", "9"],
  ["2", "6", "seven", "eight"],
  ["1", "1", "1", "three", "eight"],
  ["3", "nine", "two", "two"],
  ["four", "three", "3", "seven", "8", "three"],
  ["7", "2", "six", "5"],
  ["three", "5", "5"],
  ["six", "one", "2", "8", "six"],
  ["6", "three", "eight", "two", "five"],
  ["seven", "nine", "three", "four", "9", "6"],
  ["3", "eight", "2", "7", "2", "nine", "four"],
  ["4"],
  ["5", "five", "9", "2", "4", "3", "7"],
  ["9", "five", "3", "six"],
  ["1", "3", "six", "4", "five"],
  ["six", "5", "five", "three", "1"],
  ["2", "eight"],
  ["three", "1", "seven", "4", "1", "two", "six"],
  ["eight", "three", "four", "1"],
  ["1", "eight", "eight", "seven"],
  ["4"],
  ["2", "six", "6"],
  ["eight", "one", "9"],
  ["one", "6", "9"],
  ["5", "two"],
  ["two", "9", "three"],
  ["8", "3", "nine", "7", "one"],
  ["seven", "9", "two", "3"],
  ["seven", "3"],
  ["6"],
  ["one", "4", "8", "5"],
  ["six", "four", "7", "five", "4", "1", "seven", "two"],
  ["4", "eight", "2", "six", "two"],
  ["2", "2", "2"],
  ["nine", "1"],
  ["eight", "six", "5", "3", "4", "one"],
  ["nine", "3"],
  ["five", "3", "3"],
  ["four", "9", "4", "five", "five", "5"],
  ["six", "3"],
  ["5", "one", "6", "1"],
  ["2", "five", "eight", "6", "3", "six"],
  ["6", "3", "one", "eight", "seven", "five", "8", "7"],
  ["7", "seven", "six", "4"],
  ["4", "five", "seven", "9"],
  ["9", "one", "one"],
  ["eight", "nine", "5", "6", "1", "6", "five"],
  ["4", "two", "6", "five", "six"],
  ["1", "5"],
  ["1", "three"],
  ["4", "four", "seven", "1", "seven", "7"],
  ["nine", "6", "five", "7", "2", "five"],
  ["six", "three", "nine", "eight", "eight", "9", "two"],
  ["seven", "8", "2", "4"],
  ["8", "eight"],
  ["seven", "1", "5", "3", "nine", "7", "two"],
  ["4", "nine", "five"],
  ["2", "seven", "8", "7"],
  ["1"],
  ["9"],
  ["four", "three", "7", "2", "three", "eight", "seven"],
  ["four", "2", "1", "seven", "2"],
  ["6", "five", "1", "2", "5"],
  ["eight", "3", "2"],
  ["9", "five", "eight"],
  ["one", "2", "5"],
  ["1", "five", "eight", "8", "4", "nine", "2"],
  ["9"],
  ["7", "one", "nine"],
  ["8", "seven", "3"],
  ["7", "1", "6", "8", "6", "3"],
  ["one", "5", "9"],
  ["three", "2"],
  ["6", "4", "six", "eight", "eight"],
  ["five", "7", "6", "7", "8", "three", "seven"],
  ["5", "five", "1"],
  ["4", "three"],
  ["7", "9"],
  ["one", "7", "eight", "3", "8", "two", "3"],
  ["7"],
  ["two", "1", "3", "4", "six"],
  ["3", "2"],
  ["3", "four", "8", "4", "eight", "9"],
  ["five", "5", "seven", "three", "7"],
  ["one", "9"],
  ["eight", "nine", "6", "7"],
  ["4", "four", "three", "seven"],
  ["one", "six", "5", "four", "9"],
  ["2", "9", "7", "one", "six"],
  ["7", "five", "6", "six", "seven", "two", "seven"],
  ["four", "nine", "4", "7", "3"],
  ["7", "9", "two"],
  ["3", "3"],
  ["five", "seven", "3", "seven"],
  ["8", "eight", "1"],
  ["1", "eight", "one", "7", "3", "one", "1", "nine"],
  ["one", "9", "6", "nine"],
  ["1"],
  ["two", "5", "five", "eight", "two"],
  ["5", "nine"],
  ["six", "9"],
  ["one", "2", "4", "two", "8", "nine"],
  ["2", "8", "five", "9", "eight"],
  ["2", "4", "two", "six", "eight", "seven", "four", "7"],
  ["2", "four"],
  ["seven", "7", "five", "four"],
  ["five", "7"],
  ["5", "9", "one", "6", "2"],
  ["three", "nine", "7"],
  ["nine", "five", "7"],
  ["4", "7", "six", "9", "six"],
  ["5", "9", "four", "seven", "four", "6"],
  ["7", "1", "six", "four", "nine"],
  ["9", "three"],
  ["six", "three", "5"],
  ["eight", "six", "1", "four"],
  ["eight", "two", "9", "nine", "eight"],
  ["9", "2", "6"],
  ["four", "five", "one", "eight", "6"],
  ["nine", "eight", "6", "six"],
  ["seven", "four", "nine", "4"],
  ["seven", "7", "8", "5", "6", "9", "six", "two"],
  ["one", "9", "five", "four"],
  ["4", "seven", "one", "one", "1"],
  ["eight", "four", "1", "four"],
  ["5", "five", "five", "5"],
  ["5", "one", "9"],
  ["two", "six", "9", "4"],
  ["1", "two"],
  ["3"],
  ["four", "1", "seven"],
  ["7", "eight", "3"],
  ["one", "four", "nine", "4"],
  ["5", "two", "6", "1", "5", "eight", "1", "six"],
  ["4", "four", "five"],
  ["four", "1", "one", "five", "9"],
  ["seven", "one", "2", "three", "three", "1", "2"],
  ["three", "nine", "7", "9", "2"],
  ["8"],
  ["2", "8", "two", "five", "eight"],
  ["9", "3", "4", "four", "1", "nine"],
  ["6", "three", "9", "four"],
  ["2", "seven", "7", "9", "six"],
  ["5", "eight", "3", "three", "eight"],
  ["four", "1", "7", "three", "two"],
  ["one", "8", "seven"],
  ["8", "two", "2", "3"],
  ["two", "nine", "3", "2", "five"],
  ["7", "9"],
  ["seven", "one", "9", "1", "five"],
  ["six", "one", "3"],
  ["6", "one"],
  ["eight", "8", "6", "9", "five", "six"],
  ["seven", "eight", "nine", "7", "three", "three", "2"],
  ["6", "3", "three", "seven"],
  ["one", "1", "six"],
  ["8", "seven", "5", "5"],
  ["8", "5", "1", "7"],
  ["one", "three", "3", "four", "one", "five", "7", "six"],
  ["1", "two", "2", "five", "9", "4", "one"],
  ["four", "five", "five", "nine", "9", "4"],
  ["two", "5", "4", "two", "1", "nine", "six"],
  ["8"],
  ["two", "4"],
  ["one", "1", "1"],
  ["8", "2", "2"],
  ["6"],
  ["three", "9", "9", "5"],
  ["9", "1"],
  ["three", "9"],
  ["six", "1", "8", "3", "six", "1", "2"],
  ["1", "6", "8", "six", "9", "one"],
  ["2"],
  ["3", "4", "five", "4", "four"],
  ["seven", "4", "six", "seven", "2"],
  ["1", "3", "eight", "six", "eight", "seven", "three"],
  ["three", "2", "nine", "2", "6"],
  ["8", "six", "eight"],
  ["four", "2", "6"],
  ["2", "five", "five", "four", "5"],
  ["3", "1"],
  ["3", "1"],
  ["nine", "1", "9", "seven", "9", "5"],
  ["9", "7", "one"],
  ["seven", "five", "five", "three", "2"],
  ["5", "seven", "six"],
  ["nine", "one", "three", "four", "nine", "seven", "1"],
  ["four", "seven", "4", "9", "three"],
  ["9", "6", "1"],
  ["seven", "2", "8", "4", "3", "6"],
  ["3", "6", "three", "four"],
  ["four", "6", "7", "six", "5", "1", "9"],
  ["1", "one", "one"],
  ["6", "9", "4", "four", "8", "eight", "8"],
  ["two", "5", "4", "eight", "8", "five"],
  ["five", "1", "three", "1", "six", "8"],
  ["five", "5"],
  ["3", "four"],
  ["4", "9", "seven"],
  ["five", "two", "6", "3", "three"],
  ["9", "three", "8", "1"],
  ["9", "4", "4"],
  ["3", "two", "one", "two"],
  ["9", "8", "7", "2", "seven"],
  ["five", "5"],
  ["7"],
  ["two", "7"],
  ["3", "six", "3", "6"],
  ["5"],
  ["five", "2", "two", "2"],
  ["8", "nine", "7", "6", "5", "3", "seven"],
  ["4", "3", "eight", "six", "six"],
  ["8", "3", "8"],
  ["six", "seven", "8", "4", "5", "2"],
  ["five", "1", "5", "8", "four"],
  ["1", "five", "4", "9", "nine", "nine"],
  ["three", "9"],
  ["3", "seven"],
  ["2"],
  ["four", "nine", "five", "8", "7", "6", "six"],
  ["one", "3", "three", "1"],
  ["1", "two"],
  ["five", "six", "six", "2", "one", "nine"],
  ["six", "7", "six", "three", "three"],
  ["6", "2", "one"],
  ["seven", "seven", "7", "7", "one", "nine"],
  ["7", "two", "1", "nine"],
  ["5"],
  ["5", "seven", "six", "3"],
  ["eight", "six", "8", "2"],
  ["8", "seven", "6", "1"],
  ["five", "1", "one"],
  ["four", "eight", "7", "six"],
  ["6", "three"],
  ["8", "seven", "two", "5", "two", "5"],
  ["8"],
  ["one", "6", "7", "nine", "6", "6"],
  ["3", "6", "three"],
  ["four", "4", "nine", "nine", "three"],
  ["9", "3", "seven", "two", "six", "9", "4"],
  ["one", "1", "two", "9", "9"],
  ["three", "5", "four"],
  ["3", "9", "eight", "five", "one", "five"],
  ["nine", "1"],
  ["4", "eight", "1", "8", "three"],
  ["5", "8", "9", "1", "four", "four"],
  ["3", "seven", "8", "seven", "9"],
  ["one", "three", "7", "eight", "one", "5"],
  ["one", "3", "9", "7", "eight", "four", "eight", "6"],
  ["eight", "three", "3", "two"],
  ["two", "1", "one", "five", "nine", "8", "nine"],
  ["2"],
  ["one", "seven", "7", "7", "9"],
  ["9", "3", "six", "3"],
  ["5", "5", "8", "4", "nine", "seven"],
  ["5", "9", "seven"],
  ["three", "4", "3", "4"],
  ["5", "6", "five", "1", "1"],
  ["3", "eight", "1", "eight"],
  ["six", "2"],
  ["5", "4", "five", "eight"],
  ["3", "four", "5"],
  ["one", "nine", "7"],
  ["five", "three", "5", "eight"],
  ["2", "six", "4"],
  ["one", "2", "5", "eight", "four", "three", "8"],
  ["6", "nine", "three"],
  ["three", "4", "6", "eight"],
  ["eight", "6", "nine"],
  ["one", "three", "9"],
  ["five", "nine", "eight", "seven", "3", "2"],
  ["2", "one"],
  ["6", "eight"],
  ["3", "two", "8", "8"],
  ["four", "8"],
  ["eight", "8", "eight"],
  ["8", "seven", "nine", "eight", "6", "one"],
  ["six", "1", "nine", "seven", "5"],
  ["7", "four", "4", "7", "7", "three", "one", "two"],
  ["five", "1", "8"],
  ["two", "eight", "5", "1", "6", "five"],
  ["six", "2"],
  ["eight", "seven", "3", "two", "6"],
  ["6", "nine", "3"],
  ["7", "one", "two", "eight", "4", "6"],
  ["5", "5", "eight", "seven", "five", "four"],
  ["6", "two", "5"],
  ["five", "1", "seven"],
  ["9", "three", "nine", "3", "seven", "6"],
  ["one", "2"],
  ["6"],
  ["six", "3"],
  ["eight", "3", "1", "4"],
  ["3", "two"],
  ["6", "3"],
  ["eight", "5", "one"],
  ["7", "6", "seven", "5", "4", "nine"],
  ["five", "9", "5", "three", "seven"],
  ["7", "5"],
  ["five", "7", "8", "seven", "1"],
  ["4", "1", "4"],
  ["two", "6", "9", "nine"],
  ["six", "seven", "6", "one", "three", "four", "7", "six"],
  ["eight", "seven", "4", "one", "1", "7"],
  ["9", "two", "three", "four"],
  ["8", "4"],
  ["4", "6", "six", "six", "4"],
  ["4", "2", "7", "4", "eight", "1"],
  ["three", "2", "6", "nine"],
  ["2", "six", "nine", "6"],
  ["9", "1"],
  ["eight", "6", "three", "8", "7"],
  ["3", "4", "five", "four", "2"],
  ["3", "9", "seven", "eight"],
  ["7", "seven", "four", "five"],
  ["nine", "7", "four", "two", "1", "9"],
  ["2", "1", "5", "nine"],
  ["four", "8", "two", "six", "seven", "eight"],
  ["four", "3", "one", "8", "eight"],
  ["eight", "three", "six", "5"],
  ["7", "four", "five"],
  ["three", "2", "7"],
  ["eight", "1"],
  ["four", "6", "4", "two"],
  ["7", "9", "1", "9"],
  ["five", "four", "4", "six", "nine", "eight", "five"],
  ["2", "8", "7", "eight", "9"],
  ["6", "6", "4", "two"],
  ["seven", "6", "1"],
  ["6", "five", "five"],
  ["8", "seven", "8", "three", "eight", "two"],
  ["3", "9", "7", "2", "1"],
  ["8", "five"],
  ["2"],
  ["two", "nine", "5", "7", "3", "five", "two", "1", "six", "five"],
  ["6", "9", "six"],
  ["2", "one", "2", "4", "three"],
  ["1", "four", "6", "5", "six", "2"],
  ["7", "seven", "6", "six", "3"],
  ["six", "9", "two", "one", "4", "six"],
  ["one", "2", "8", "five"],
  ["8", "six", "three", "9", "4"],
  ["9", "1"],
  ["5", "two", "one", "1", "4", "eight", "6"],
  ["6", "2", "9", "7"],
  ["3", "five", "7", "two", "seven"],
  ["8", "6", "3", "eight"],
  ["two", "four", "7"],
  ["6", "five", "five", "6", "eight", "six"],
  ["seven", "6", "nine", "5"],
  ["7", "four", "nine", "9"],
  ["eight", "8", "four", "four", "five", "one", "four"],
  ["one", "6", "1", "four"],
  ["2", "nine", "seven", "four", "4"],
  ["two", "1", "8"],
  ["5", "nine", "six", "4", "8", "4", "9"],
  ["one", "5", "six", "9", "8", "3", "three", "4"],
  ["1", "8", "nine", "one", "1", "8"],
  ["6", "five", "9", "2", "eight", "6"],
  ["4", "1", "1", "6", "3", "one", "1"],
  ["9", "three", "7"],
  ["8", "2", "six"],
  ["9"],
  ["8", "8", "three", "1", "one"],
  ["8", "4", "1", "eight"],
  ["4"],
  ["four", "4", "9", "five", "seven"],
  ["6", "5", "five"],
  ["two", "3", "4", "four", "nine"],
  ["5", "two", "3"],
  ["five", "5"],
  ["three", "9", "three", "four"],
  ["9", "seven", "3"],
  ["five", "3", "7", "three", "1"],
  ["two", "two", "5", "9", "five", "six"],
  ["six", "three", "9", "two", "3", "6", "three", "nine"],
  ["eight", "1", "three", "three", "four"],
  ["5", "two", "six"],
  ["1", "3", "9", "3", "four"],
  ["2", "eight", "one"],
  ["six", "4", "five", "9"],
  ["1", "5", "1", "3", "1", "eight"],
  ["9", "six", "two"],
  ["2", "five", "four", "two", "one", "8"],
  ["nine", "one", "5", "one", "six"],
  ["2", "eight", "3", "eight", "6", "7"],
  ["4", "4", "4", "2", "nine", "five"],
  ["8", "1", "2", "5"],
  ["3"],
  ["9", "four", "4", "eight", "5", "eight", "two"],
  ["6", "1"],
  ["7", "three"],
  ["eight", "1", "4", "three", "6", "7"],
  ["5", "9", "nine"],
  ["six", "2"],
  ["9", "six", "1", "four", "six", "7", "seven"],
  ["eight", "nine", "one", "7", "four", "four"],
  ["four", "eight", "three", "7", "three"],
  ["two", "two", "4", "two"],
  ["3", "1", "4", "one", "4", "seven"],
  ["four", "nine", "nine", "4", "five"],
  ["four", "2", "5", "2"],
  ["4", "5", "6"],
  ["one", "eight", "9", "9"],
  ["8", "3", "2"],
  ["1", "four", "2", "1", "six", "six", "5"],
  ["7", "3"],
  ["5", "two", "6", "2"],
  ["eight", "4", "5"],
  ["1", "six", "three", "eight", "one", "7"],
  ["3", "two", "7", "six", "eight"],
  ["6"],
  ["4", "five", "8"],
  ["1"],
  ["four", "3"],
  ["3", "9", "5", "seven", "7", "1"],
  ["three", "8", "7"],
  ["1", "five", "nine", "nine", "9"],
  ["one", "4", "seven", "4", "5"],
  ["5", "five", "5"],
  ["3", "one", "2", "7", "5", "three"],
  ["eight", "6"],
  ["1", "3", "9"],
  ["four", "9", "three", "four", "eight"],
  ["one", "9", "three", "two", "one", "4"],
  ["4"],
  ["2", "3"],
  ["eight", "6", "1"],
  ["5", "seven", "four", "5", "8", "3"],
  ["8", "nine", "one", "six", "three"],
  ["3", "1", "five", "four", "four"],
  ["seven", "9", "3", "four", "six", "9"],
  ["8"],
  ["4"],
  ["four", "seven", "two", "7"],
  ["4", "two", "two", "6", "2"],
  ["one", "2", "six", "one", "three", "three", "8", "one"],
  ["4", "seven", "9", "9"],
  ["9", "two", "nine"],
  ["3"],
  ["5"],
  ["7", "five", "five"],
  ["8", "three", "6"],
  ["six", "2", "three", "five"],
  ["5", "1", "one"],
  ["3", "7"],
  ["8", "nine"],
  ["eight", "three", "eight", "2", "7", "six"],
  ["1", "2", "8", "1", "4", "three"],
  ["7", "6", "1", "eight", "five"],
  ["one", "3"],
  ["9", "9", "seven", "4", "nine"],
  ["1", "one", "2", "3", "one", "2"],
  ["4", "2", "5", "five", "5", "9", "two"],
  ["eight", "4", "4", "eight"],
  ["1"],
  ["9"],
  ["six", "6", "2", "6", "one", "eight"],
  ["9", "7", "four", "2"],
  ["three", "8", "seven", "three", "7", "three"],
  ["2", "four"],
  ["2"],
  ["1", "7", "7"],
  ["5", "5"],
  ["one", "5"],
  ["9", "two"],
  ["2", "6"],
  ["eight", "2", "9", "9", "eight"],
  ["2", "one", "9", "8", "6"],
  ["6", "two", "4", "eight"],
  ["5", "2", "seven"],
  ["four", "seven", "8", "four", "six"],
  ["6"],
  ["7", "six", "3"],
  ["8", "2", "3", "1", "four", "7"],
  ["6", "nine", "four", "four"],
  ["two", "two", "4", "3", "7", "4"],
  ["4", "7", "six", "three"],
  ["9", "three", "nine", "8"],
  ["seven", "two", "9", "6", "six", "5"],
  ["seven", "three", "one", "2", "four", "six", "three"],
  ["four", "6", "seven", "4", "8"],
  ["4", "3", "3"],
  ["two", "six", "seven", "6", "3"],
  ["7", "five", "two", "two"],
  ["nine", "7", "four", "one"],
  ["2"],
  ["7", "7", "nine", "6", "3", "8"],
  ["seven", "7", "four", "four", "2"],
  ["2", "3", "six", "six"],
  ["one", "4", "two", "five", "one"],
  ["four", "five", "five", "6", "two", "7"],
  ["7", "8", "4", "1", "eight"],
  ["3", "five", "8", "5", "9", "five", "7", "2", "9"],
  ["1", "four", "five"],
  ["2", "9", "six", "three", "3", "six", "four"],
  ["4"],
  ["4", "7"],
  ["7"],
  ["two", "five", "1"],
  ["eight", "three", "2", "two"],
  ["9", "5", "four", "three"],
  ["2", "9"],
  ["4", "four", "2", "9", "seven", "two", "1"],
  ["2", "one", "5"],
  ["6"],
  ["five", "nine", "2", "nine", "5", "nine"],
  ["3"],
  ["eight", "6", "9", "eight"],
  ["six", "5"],
  ["one", "7", "5", "six"],
  ["4", "7", "8", "5"],
  ["one", "two", "8", "six"],
  ["three", "3", "one", "one", "two"],
  ["nine", "8", "two", "five", "8"],
  ["8", "8", "three", "4"],
  ["one", "4", "8", "8", "1", "9"],
  ["two", "9", "nine", "2", "three", "1", "3"],
  ["two", "3", "3"],
  ["1", "five", "six", "one", "six"],
  ["3", "2"],
  ["3", "2", "3"],
  ["six", "8", "six", "6"],
  ["one", "5", "7", "one", "one"],
  ["nine", "4", "one"],
  ["three", "six", "5", "five"],
  ["eight", "4", "eight", "six", "1"],
  ["2"],
  ["eight", "1"],
  ["one", "two", "2", "1", "2"],
  ["8", "five", "three"],
  ["seven", "3", "9", "5", "8", "6"],
  ["2", "1", "four", "5"],
  ["four", "1", "three", "three"],
  ["5", "9", "4", "4", "three"],
  ["5", "8", "5", "1", "8"],
  ["4", "eight", "4"],
  ["six", "5", "two", "4", "2", "3", "5", "1"],
  ["three", "1", "6", "three", "3", "3"],
  ["4", "6", "5", "5"],
  ["six", "one", "one", "5", "nine", "2"],
  ["3", "two"],
  ["three", "4", "9", "seven", "seven", "six"],
  ["1", "9", "8", "9", "6", "1"],
  ["two", "6", "9", "9", "5"],
  ["2", "five", "6"],
  ["two", "5"],
  ["seven", "1", "seven", "nine"],
  ["4"],
  ["4", "nine", "1", "8", "6", "two"],
  ["eight", "7", "9", "5", "7", "seven"],
  ["four", "1", "one", "9", "one", "eight", "4"],
  ["2", "one", "five", "four", "4"],
  ["three", "7", "8"],
  ["9", "eight", "6", "six"],
  ["3"],
  ["4", "three", "1", "one", "six", "3", "six", "6"],
  ["7", "nine", "eight", "eight", "9"],
  ["two", "3"],
  ["8", "two", "1", "4"],
  ["1", "one"],
  ["six", "6", "9", "8"],
  ["5", "9"],
  ["5", "2", "eight", "six", "3", "9", "9"],
  ["nine", "six", "4", "9", "8"],
  ["1", "five", "6", "three"],
  ["3", "five", "1"],
  ["3", "one"],
  ["one", "2"],
  ["5", "3", "4", "8"],
  ["2", "seven", "one", "two", "five"],
  ["two", "6"],
  ["five", "eight", "9"],
  ["9", "2", "1", "7", "five", "four", "six"],
  ["1", "seven", "6", "five"],
  ["5", "5", "five"],
  ["9", "five", "5", "4", "3", "8"],
  ["6", "1", "9", "three", "three"],
  ["2", "four"],
  ["5", "four", "four"],
  ["7", "9", "seven", "7"],
  ["9", "2", "six", "4", "seven", "four"],
  ["four", "nine", "nine", "2", "one"],
  ["six", "4", "five"],
  ["6", "four", "1", "6", "two"],
  ["2", "five", "five", "9"],
  ["4", "5", "two", "8"],
  ["8", "4", "five", "9", "eight", "9", "eight", "one"],
  ["6", "5"],
  ["4"],
  ["three", "9"],
  ["three", "1", "four", "six", "7", "four"],
  ["9", "one", "3", "three", "two"],
  ["7", "six", "8", "3", "9", "4", "two"],
  ["9", "4", "seven", "four", "nine"],
  ["5", "2"],
  ["nine", "3"],
  ["nine", "6", "six", "five", "9"],
  ["six", "eight", "3", "6"],
  ["seven", "9", "six"],
  ["eight", "5", "two"],
  ["5", "four", "4", "five", "3", "8", "two", "nine"],
  ["4", "8", "3", "seven"],
  ["three", "9", "three", "6", "4", "five", "9"],
  ["four", "4", "four"],
  ["six", "three", "six", "8", "8", "six"],
  ["6", "five", "eight", "2", "8", "four", "four"],
  ["2", "5", "2", "four", "eight", "four", "7"],
  ["seven", "six", "5", "8", "3", "4"],
  ["2", "two"],
  ["8"],
  ["nine", "7"],
  ["eight", "four", "six", "3", "1", "two"],
  ["1", "four", "nine"],
  ["3", "one"],
  ["4", "9"],
  ["4", "9", "1", "eight"],
  ["three", "2", "three", "2", "1"],
  ["4"],
  ["6", "nine"],
  ["5", "eight", "six", "eight"],
  ["2", "7", "8", "two", "seven"],
  ["three", "3", "nine"],
  ["six", "4", "8", "three"],
  ["five", "six", "1", "2", "3", "six"],
  ["1", "5", "three"],
  ["9", "four", "four", "3"],
  ["4", "one", "7"],
  ["nine", "one", "1", "6", "three"],
  ["nine", "1", "two", "7"],
  ["9", "5", "3", "3", "nine", "one", "2"],
  ["six", "3", "nine", "two"],
  ["five", "4", "3", "5"],
  ["9", "9", "six", "2", "5"],
  ["four", "7", "1", "6", "4", "2"],
  ["7", "3", "5"],
  ["6", "5", "five", "8", "9", "7"],
  ["three", "one", "9", "5", "8", "two"],
  ["5", "five", "8"],
  ["4", "4", "five", "3", "7", "five", "five"],
  ["five", "5", "four", "8"],
  ["9", "five", "1", "6", "eight", "5", "8"],
  ["eight", "7", "four", "four", "6", "4", "six", "one"],
  ["two", "four", "5", "one"],
  ["8", "3", "three"],
  ["three", "three", "four", "six", "6", "2", "one"],
  ["8", "five", "seven", "nine", "2", "seven", "2"],
  ["four", "seven", "eight", "7", "4"],
  ["3", "8"],
  ["1", "5", "five", "three", "nine", "8"],
  ["four", "three", "8"],
  ["3", "one", "eight", "four"],
  ["7", "six", "five", "one"],
  ["4"],
  ["two", "eight", "5", "9"],
  ["two", "two", "five", "8"],
  ["5", "four", "eight", "9"],
  ["8", "7", "two", "three", "5", "nine"],
  ["four", "four", "1", "five", "two", "five", "2"],
  ["five", "7", "5"],
  ["4", "7", "9"],
  ["1", "8", "four", "8"],
  ["eight", "1"],
  ["three", "2", "five", "four", "seven"],
  ["5", "5"],
  ["8", "8", "4", "7", "eight", "5", "3"],
  ["one", "5", "seven"],
  ["seven", "seven", "1", "2", "eight"],
  ["2", "three", "3", "four", "seven"],
  ["3", "9", "seven"],
  ["eight", "7", "four"],
  ["six", "1", "4", "9"],
  ["four", "eight", "1", "three"],
  ["9", "nine", "7"],
  ["one", "eight", "3", "6"],
  ["six", "1", "4", "eight", "five", "four", "4"],
  ["three", "three", "2", "six", "7"],
  ["nine", "2", "two", "2", "5"],
  ["nine", "five", "seven", "1"],
  ["4", "3", "7", "five", "8"],
  ["6", "6", "nine", "one", "1"],
  ["nine", "4", "one", "five", "9", "7"],
  ["two", "1", "nine"],
  ["nine", "five", "6", "2"],
  ["eight", "8", "nine", "5"],
  ["four", "9", "three", "3", "nine", "5"],
  ["4", "3", "six", "3", "two", "eight"],
  ["four", "1", "two", "six", "six", "6", "7"],
  ["four", "five", "8", "nine", "six", "eight"],
  ["5", "nine", "1", "8", "three", "6", "five"],
  ["5", "1", "one", "2", "6"],
  ["6", "8", "7", "1", "2", "three"],
  ["6", "2", "nine", "seven"],
  ["4", "five", "two", "four", "2", "8", "seven"],
  ["2", "7", "4", "four"],
  ["4", "nine", "2", "one"],
  ["eight", "7", "4", "eight"],
  ["1", "one", "3", "3", "eight", "2"],
  ["5", "nine", "1", "9", "eight", "five", "8", "8"],
  ["1", "1", "one", "2", "six"],
  ["5", "1", "one"],
  ["9", "6"],
  ["9", "three", "seven", "5"],
  ["seven", "6", "2"],
  ["three", "one", "five", "two", "9", "1", "three", "6"],
  ["three", "3"],
  ["6"],
  ["9", "8", "four", "5", "nine", "3"],
  ["2", "6", "7", "two", "8", "8", "4", "one"],
  ["1", "4", "1", "eight"],
  ["one", "3", "one", "6", "2"],
  ["five", "5", "six", "1"],
  ["one", "five", "five", "5", "six"],
  ["three", "seven", "three", "2"],
  ["one", "1", "4", "seven"],
  ["7", "seven", "3", "nine", "eight", "two"],
  ["one", "one", "7", "three", "3"],
  ["two", "two", "three", "five", "two", "9"],
  ["five", "nine", "1", "9", "seven", "8", "two", "4"],
  ["seven", "five", "5", "1", "4"],
  ["four", "five", "3", "2"],
  ["three", "4", "eight", "two", "9"],
  ["eight", "1"],
  ["2", "nine", "5", "three"],
  ["6"],
  ["seven", "8", "nine", "2"],
  ["three", "three", "four", "8"],
  ["6", "6", "3", "three"],
  ["two", "8", "nine"],
  ["six", "3"],
  ["4", "four", "two", "8", "6", "two"],
  ["4", "eight", "seven", "eight", "5", "6"],
  ["four", "9"],
  ["one", "six", "8", "two", "2"],
  ["three", "one", "7", "1", "four"],
  ["one", "7", "five", "8"],
  ["4", "2", "one", "1"],
  ["6", "3"],
  ["eight", "2", "six", "3", "8", "3"],
  ["eight", "3", "8"],
  ["3", "3", "6", "2"],
  ["3"],
  ["1", "nine", "6", "five", "nine", "3", "7"],
  ["4", "nine", "four", "2", "nine", "3"],
  ["five", "1"],
  ["one", "4"],
  ["two", "8", "five", "two"],
  ["9"],
  ["7", "9", "5", "two", "3"],
  ["5", "1", "one"],
  ["three", "2", "6", "3", "four"],
  ["8", "6", "seven"],
  ["5", "8", "5"],
  ["eight", "seven", "5", "1", "1"],
  ["one", "8", "eight", "5", "7", "six", "1", "four"],
  ["2", "5", "5", "four", "one", "7", "2"],
  ["one", "1", "two", "7", "one", "6"],
  ["four", "nine", "2", "six"],
  ["seven", "two", "4"],
  ["2", "5", "eight", "four", "one", "two"],
  ["seven", "five", "seven", "4"],
  ["1", "8", "3", "five", "5", "eight"],
  ["seven", "five", "seven", "9"],
  ["three", "3"],
  ["one", "2", "3", "7"],
  ["5", "six", "six", "6"],
  ["2", "8", "7"],
  ["six", "seven", "nine", "4"],
  ["five", "six", "7"],
  ["7", "3", "7", "six", "8", "one"],
  ["6", "5", "8", "one", "nine", "two"],
  ["6", "2", "6"],
  ["7"],
  ["two", "one", "9", "three", "8"],
  ["3", "six", "three", "2"],
  ["three", "8", "six"],
  ["9", "4", "9", "7", "9", "one"],
  ["3", "three", "six"],
  ["8"],
  ["3", "five", "nine", "two"],
  ["9"],
  ["four", "five", "four", "one", "9", "four", "9", "nine"],
  ["5", "one", "5"],
  ["one", "6", "6", "four", "2", "8", "1"],
  ["one", "8", "7", "1"],
  ["five", "3", "eight", "six"],
  ["4", "three", "1", "9", "four", "5"],
  ["8", "three", "four", "4"],
  ["1", "9", "five", "6", "8"],
  ["six", "two", "9", "1", "four", "two"],
  ["1"],
  ["two", "four", "seven", "2"],
  ["one", "1", "two"],
  ["nine", "2"],
  ["1", "four"],
  ["1", "7", "3", "one", "eight", "5", "9", "7"],
  ["3"],
  ["2", "5", "1", "3"],
  ["3", "five", "9", "1", "eight", "one"],
  ["2", "seven", "one", "eight"],
  ["1", "one", "5", "eight", "four", "5", "eight"],
  ["4", "1"],
  ["one", "8", "eight"],
  ["9", "three", "1"],
  ["5", "8", "nine", "two", "nine", "8", "three", "7"],
  ["nine", "6", "3"],
  ["2", "3", "seven", "7"],
  ["4", "1", "2", "7", "9", "1", "2"],
  ["eight", "three", "three", "1", "2", "nine", "two", "1"],
  ["6", "2", "7", "three"],
  ["1", "7", "1"],
  ["three", "4", "two", "4", "seven", "eight"],
  ["5", "8", "nine", "6", "5"],
  ["3", "5", "5", "8"],
  ["3", "2", "1", "1"],
  ["9", "6", "9", "five"],
  ["6", "7"],
  ["6"],
  ["eight", "9", "9", "9"],
  ["four", "six", "three", "9"],
];

for (const numbers of lines) {
  let firstNumber = numbers[0];
  let lastNumber = numbers[numbers.length - 1];
  if (isNaN(firstNumber)) {
    firstNumber = NUMBERS_BY_WORD[firstNumber];
  }
  if (isNaN(lastNumber)) {
    lastNumber = NUMBERS_BY_WORD[lastNumber];
  }
  console.log(`${firstNumber}${lastNumber}`);
}
